### ISSUE TITLE
Error installing on .Net standard 

### ISSUE THREAD

**Issue by cgomezm** [Xamarians/Xamarians.Geolocator#1]
Hi. I'm trying to install the component on a .netstandard shared project and i'm getting this error: 
Restored using '.NETFramework, Version=4.61' instead of the target framework'

**Comment by Xamarians** [comment]
Hi @cgomezm 

Xamarin.Forms is using.NETStandard as the Target Framework, not .NETFramework. Here you can take the reference to your problem.

https://stackoverflow.com/questions/42939454/what-is-the-difference-between-net-core-and-net-standard-class-library-project

And for .NetStandered Document
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
